auto_reply_task:
  description: >
    处理{comment_list}中的每个评论，每个评论包含'comment_id'标识评论ID, 'content'字段，表示评论的内容。
    对于每个评论，根据评论的内容，生成回复。
    回复的内容，需要确保与评论的内容相关，并且使用人类化的语言，可以使用emoji等表情包，避免使用过于正式的措辞。
    回复的内容，需要确保不超过50个字符。
    如果评论涉及需要特定知识或超出您能力范围的问题，而您不确定如何准确回答，则输出"请求人工干预"，然后清楚地解释您认为需要人工干预的具体原因。
    充分利用标题:{title}, 文案:{desc}, 关键词:{tag_list}等信息输入。

    步骤:
    1. 对于每条评论，提取核心问题
    2. 使用 FAISS知识库工具查询相关知识（必须执行此步骤）
    3. 根据查询结果和你的专业知识，组织一个内容相关的，有专业度的，有温情的回答
    4. 在回答中引用知识库提供的信息

  expected_output: >
    json格式, 每条评论包含三个字段：
    "target_comment_id": [目标评论ID],
    "target_comment": [目标评论内容],
    "reply": [你的回复内容],


  agent: reply_assistant