video_copy_writer_task:
  description: >
    任务描述:
    给你关于自有账号的定位，本次选题，目标受众。
    以及对于目标爆款视频的剧情梗概、分镜脚本、分析报告。
    请你将二者进行有机结合，产出服务于自身创作的策划提案、视频文案、分镜脚本。

    #输入信息包括：
    ## 自有账号信息
    定位：{account_position}
    选题：{video_topic}
    目标受众：{target_audience}

    ## 爆款视频信息
    剧情梗概：{video_story_summary}
    分镜脚本：{video_story_board}
    分析报告：{video_analysis_report}


    # 约束:
    - 保持借鉴的同时，尊重原创性，保证明显抄袭内容占比小于50%。
    - 对视频结构、主体、视觉、文案、人设、场景、节奏等要素进行，在对爆款原因充分保留的前提下，进行有针对性的二次创作。

  expected_output: >
    包括策划提案、视频文案、分镜脚本

    ## 策划提案：
    作为项目发起的蓝图，重点回答为什么要做？为什么要这么做？策略性强，说服力是关键，使参与方达成共识，以立项为目标。
    可以包含以下内容：
    - 创作目的：为什么要做这个视频？
    - 目标人群：视频是拍给谁看的？他们的特征、兴趣、痛点是什么？
    - 核心创意：用简洁的语言描述视频的核心想法或故事梗概
    - 提供价值：给目标人群能提供什么样的价值？他们为什么会想观看？
    - 内容方向和风格类型：视频大致会讲什么内容？采用什么风格？整体氛围是怎样的？

    ## 视频文案：
    是内容的核心和骨架，重点在于"表达什么"，它将创意具象化为文字内容和叙事结构。
    通常包括以下内容：
    - 标题/主体
    - 开场/hook：如何在最短时间内抓住观众注意力？
    - 主体内容：
      - 场景/段落划分
      - 画面/视觉描述（简要，不需要分镜那么细致）
      - 人物
      - 对话/旁白/字幕：对应的文字
    - 结尾/CTA 
    - 音乐/音效建议：进行必要的描述，作为后期剪辑时挑选和判断依据
    - 时长预估

    ## 分镜脚本：
    作为拍摄执行的详细指南，格式参考如下：
    镜号 | 场景描述 | 景别 | 拍摄角度 | 画面内容 | 对白/旁白 | 时长 | 音乐/音效 | 备注
    --- | --- | --- | --- | --- | --- | --- | --- | ---
    1 | 办公室/模特特写 | 特写 | 正面/平视 | 模特突然抬头，表情惊讶 | "你知道吗？这款产品竟能让生活变得如此简单！" | 3秒 | 激励音乐轻快 | 快节奏吸睛
    2 | 办公室/抽屉内 | 中景 | 平拍 | 模特打开抽屉，发现精美产品 | "原来我的宝藏一直藏在这里..." | 5秒 | 渐入背景音乐 | 慢推镜头

  agent: video_copy_writer_agent