multi_modal_understand_task:
  description: >
    分析图片内容，提取图片中的文字信息, 所有的 image URL 在{image_list}中.
    对于每个 image URL, 描述你看到的细节，注意提取其中的品牌名、产品名, 成分, 功效,规格, 价格,适用场景, 适用人群,活动内容等信息(可自主延展).
    多模态内容分析的结果，是为了后续组建知识库、知识图谱，以及为后续的专业化的自动回复提供信息支持。

  expected_output: >
    json格式，包含
    --图片的url, 
    --图片的分析描述信息。
  agent: multi_modal_understand_analyst


auto_reply_task:
  description: >

    处理{comment_list}中的每个评论，每个评论包含'content'字段，表示评论的内容。
    对于每个评论，根据评论的内容，生成回复。 
    回复的内容，需要确保与评论的内容相关，并且使用人类化的语言，可以使用emoji等表情包，避免使用过于正式的措辞。
    回复的内容，需要确保不超过50个字符。
    如果评论涉及需要特定知识或超出您能力范围的问题，而您不确定如何准确回答，则输出“请求人工干预”，然后清楚地解释您认为需要人工干预的具体原因。
    充分利用标题:{title}, 文案:{desc}, 关键词:{tag_list}等信息输入。


    步骤:
    1. 对于每条评论，提取核心问题
    2. 使用 FAISS知识库工具查询相关知识（必须执行此步骤）
    3. 根据查询结果和你的专业知识，组织一个内容相关的，有专业度的，有温情的回答
    4. 在回答中引用知识库提供的信息



  expected_output: >
    1. 原始评论: [评论内容]
    2. 查询过程: [FAISS知识库工具查询内容及结果]
    3. 回复内容: [你的回复]

  agent: reply_assistant
