multi_modal_understand_task:
  description: >
    Analyze all image URL in the {image_list}.
    For each image URL, describe what you see in detail.
    Focus on key visual elements, text content, and overall theme.

    
    When describing each image, include the following aspects:
    - Main objects or subjects in the image
    - Scene or setting
    - Colors and visual elements
    - Any text visible in the image
    - Overall mood or theme of the image
    
    Focus on providing accurate, detailed descriptions that could be useful for searching or categorizing these images.
  expected_output: >
    A list containing image descriptions. Each image description contains the following information:
    - image URL
      - Main objects or subjects in the image
      - Scene or setting
      - Colors and visual elements
      - Any text visible in the image
      - Overall mood or theme of the image
    
  agent: multi_modal_understand_analyst


auto_reply_task:
  description: >
    
    Take advantage of note title, desc, tag_list , content parsed from multi_modal_understand_task, and knowledge bases.
    
    Process all comments in the {comment_list}. Each comment has a 'content' field that contains the text of the comment.
    
    Iterate through each comment content: {{comment_list.content}}.
    For the current comment, think about how to reply, ensuring that the reply is relevant to the context of the comment.
    Use a human-like tone for the reply. For example, you can use emoticons and more natural, colloquial expressions.
    Keep the generated reply to a maximum of 50 characters.
    If the comment involves questions that require specific knowledge or are beyond your capabilities (e.g., specific product purchase links, complex after-sales issues, technical questions requiring professional answers, etc.), and you are unsure how to answer accurately, output \"Request manual intervention\" followed by a clear explanation of the specific reason why you believe manual intervention is necessary.
    Encapsulate the original comment and your reply (or manual intervention request) into a dictionary with the keys 'comment' for the original comment and 'reply' for your response or manual intervention information.
    Put all the comment-reply dictionaries into a list.
    Return the final list containing all comment reply information.
  expected_output: >
    A list containing reply information, where each element is a dictionary with two fields:
    'comment' (the original comment) and 'reply' (the assistant's reply or manual intervention request).",
  agent: reply_assistant
